### ISSUE TITLE
A cheatsheet category?

### ISSUE THREAD

**Issue by aloisdg** [VPashkov/awesome-fsharp#21]
It is nice to start with a showcase :)

* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tour
* http://dungpa.github.io/fsharp-cheatsheet/ [repo](https://github.com/dungpa/fsharp-cheatsheet)
* https://learnxinyminutes.com/docs/fsharp/ [repo](https://github.com/adambard/learnxinyminutes-docs)

**Comment by VPashkov** [comment]
Hi!

Great idea. Do you want to make a PR?
If not I can do it.

**Comment by aloisdg** [comment]
@VPashkov As you want. Feel free to do it directly it will be faster :)

**Comment by VPashkov** [comment]
Done.
@aloisdg, thanks for your contribution.
